-- https://docs.google.com/document/d/1Va1tyzi7ZAyR4r28TxXzq9ELHoTP4v0dUeAeC1i2egc/edit
-- https://github.com/juancuiule/pdep-utn-cursada-2017/blob/master/Funcional/parcialWatchman.hs
-- https://github.com/matiasrizzatobusta/ParcialModelo-f-Watchman
-- https://github.com/DanteBonino/wathcmenParcial